require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '**/*.jbuilder'
    - 'node_modules/**/*'

Documentation:
  Enabled: false

LineLength:
  Max: 120

Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
